# Generated by Django 4.2.3 on 2023-07-18 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leftovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='purchased_leftovers', to=settings.AUTH_USER_MODEL)),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='for_sale_leftovers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
